#!/bin/bash

mkfs.fat -F32 /dev/nvme0n1p1
mkswap /dev/nvme0n1p2
swapon /dev/nvme0n1p2
mkfs.ext4 /dev/nvme0n1p3
mount /dev/nvme0n1p3 /mnt
echo [multilib] >> /etc/pacman.conf
echo Include = /etc/pacman.d/mirrorlist >> /etc/pacman.conf
cp mirrorlist /mnt/etc/pacman.d/mirrorlist
pacman -Syy
pacstrap /mnt base linux linux-firmware nano base-devel
genfstab -U /mnt >> /mnt/etc/fstab
cp mirrorlist /mnt/etc/pacman.d/mirrorlist
cp /etc/pacman.conf /mnt/etc/pacman.conf
mv part2 /mnt
mv moddas /mnt
arch-chroot /mnt
