#!/bin/bash


cp /etc/locale.gen /etc/locale.gen.bak
echo sv_SE.UTF-8 >> /etc/locale.gen
pacman -Syy
pacman-key --populate archlinux
timedatectl set-timezone Europe/Stockholm
locale-gen
echo LANG=sv_SE.UTF-8 > /etc/locale.conf
export LANG=sv_SE.UTF-8
echo arch-workstation > /etc/hostname
mv hosts /etc/
passwd
pacman -S grub efibootmgr xorg xorg-server gdm cinnamon networkmanager xdg-user-dirs sudo xed xreader steam libreoffice-fresh firefox gparted gnome-disk-utility nvidia nvidia-settings nvidia-utils transmission-gtk
mkdir /boot/efi
mount /dev/nvme0n1p1 /boot/efi
grub-install --target=x86_64-efi --bootloader-id=Arch --efi-directory=/boot/efi
grub-mkconfig -o /boot/grub/grub.cfg
systemctl enable gdm.service
systemctl enable NetworkManager
useradd -m -g users -G wheel,storage,power -s /bin/bash modda
passwd modda
EDITOR=nano visudo
mv /moddas /home/modda/
chmod modda +x /home/modda/moddas
su modda
echo "-----------------"
echo "All set and done!"
echo "-----------------"
