#!/bin/bash


ln -sf /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
hwclock --systohc
echo sv_SE.UTF-8 >> /etc/locale.gen
echo en_US.UTF-8 >> /etc/locale.gen
locale-gen
echo sv_SE.UTF-8 >> /etc/locale.conf
export LANG=sv_SE.UTF-8
echo KEYMAP=sv-latin1 >> /etc/vconsole.conf
pacman -Syy
pacman-key --populate archlinux
echo arch-workstation >> /etc/hostname
echo 127.0.0.1	localhost >> hosts
echo ::1		    localhost >> hosts
echo 127.0.1.1  arch-workstation >> hosts
passwd
pacman -S grub efibootmgr xorg xorg-server gdm cinnamon networkmanager xdg-user-dirs sudo gnome-terminal xed xreader fuse steam libreoffice-fresh-sv firefox gparted gnome-disk-utility nvidia nvidia-settings nvidia-utils nvidia-prime transmission-gtk
mkdir /boot/efi
mount /dev/nvme0n1p1 /boot/efi
grub-install --target=x86_64-efi --bootloader-id=Arch --efi-directory=/boot/efi
grub-mkconfig -o /boot/grub/grub.cfg
systemctl enable gdm.service
systemctl enable NetworkManager
useradd -m modda
passwd modda
xdg-user-dirs-update
EDITOR=nano visudo
mv /moddas /home/modda/moddas
su modda
echo "-----------------"
echo "All set and done!"
echo "-----------------"
