#!/bin/bash

mkfs.fat -F32 /dev/nvme0n1p1
mkswap /dev/nvme0n1p2
swapon /dev/nvme0n1p2
mkfs.ext4 /dev/nvme0n1p3
mount /dev/nvme0n1p3 /mnt
pacman -Syy
pacman -S reflector
reflector --latest 10 --sort rate --save /etc/pacman.d/mirrorlist
cp /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist
pacstrap /mnt base linux linux-firmware nano base-devel
genfstab -U /mnt >> /mnt/etc/fstab
mv part2 /mnt
mv hosts /mnt
mv modda /mnt
cp /etc/pacman.conf /mnt/etc/pacman.conf
arch-chroot /mnt
